[package]
name = "tests-extra"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
self_cell = { path=".." }
crossbeam-utils = "0.8.0"
impls = "1.0.3"
trybuild = "1.0.37"
