[package]
name = "once_self_cell"
version = "0.6.3"
authors = ["Lukas Bergdoll <lukas.bergdoll@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

description = "Safe-to-use proc-macro-free self-referential structs in stable Rust."
readme = "README.md"
documentation = "https://docs.rs/once_self_cell"

repository = "https://github.com/Voultapher/once_self_cell"
keywords = ["lazy", "lifetime", "borrowing", "self", "reference"]
categories = ["rust-patterns", "memory-management"]

include = [
    "src/*.rs",
    "Cargo.toml",
]

[dependencies]
once_cell = ">=1"

[dev-dependencies]
crossbeam-utils = "0.8.0"
trybuild = "1.0.37"